### ISSUE TITLE
some missing contacts and wrong paths

### ISSUE THREAD

**Issue by shayanb** [nexusdev/ds-token#1]
I was about to do a pull request with fixed contract paths that I noticed some contracts such as `auth.sol` is missing from the files.

some other contracts have wrong paths, e.g `/token/` and `/data/` directories
-  from front-end.sol

```
import 'auth.sol';
import 'token/controller.sol';
import 'token/event_callback.sol';
import 'token/token.sol';
```
- from controller.sol

```
 import 'auth.sol';
import 'data/approval_db.sol';
import 'data/balance_db.sol';
import 'token/erc20.sol';
import 'token/event_callback.sol';
import 'token/frontend.sol';
import 'token/token.sol';

import 'util/safety.sol';
```

**Comment by nmushegian** [comment]
dapple submodules are just git submodules but you still have to do it manually, `git submodule --init --recursive update`

it's strange that I missed the bad import paths, I could have sworn I pushed a version that passed all tests. will investigate

**Comment by stevenh512** [comment]
The biggest problem I see, is that I don't see any `ds-data` or `ds-util` repositories on GitHub. If you have a version of this that passes all tests, I'm guessing those repositories probably exist. Maybe they're not public for some reason?

There are also no submodules (`git submodule update --recursive --init` doesn't do anything) and a few include paths need to be adjusted (`auth.sol` -> `auth/auth.sol`, `token/erc20.sol` -> `erc20/erc20.sol`, `token/controller.sol` -> `controller.sol`, etc).. but even if you didn't already have a version that passes all tests, those would be trivial things to fix with a pull request if there were public `ds-data` and `ds-util` repositories.

**Comment by nmushegian** [comment]
For context, I'm right in the middle of pulling these out of here: https://github.com/nexusdev/dappsys/tree/develop/contracts

If you're getting this into it, I suggest to go ahead and use that package for development. These fragmented subpackages are also going to be turbulent as we transition to dapple v0.8 which has a backwards incompatible package/dappfile format.

**Comment by nmushegian** [comment]
also now I think this repo should have its own datastore contract definition, not sure about hoisting util or not since it is very much in flux and we just use a few safe math functions

**Comment by nmushegian** [comment]
@stevenh512 Take a look now - you'll see there is still some spaghetti since subpackages and subdirectories are indistinguishable instead of following the "./localdir" vs "package/" convention, but at least now everything is there and a pull + submodule update should give you something that passes all tests
